codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 0
    patch:
      default:
        target: 0
        threshold: 0

ignore:
  - "package-template/tests/"
  - "package-template/due.py"
  - "package-template/_version.py"
  - "package-template/info.py"
