codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 0
    patch:
      default:
        target: 0
        threshold: 0

ignore:
  - "python_course/tests/"
  - "python_course/due.py"
  - "python_course/_version.py"
  - "python_course/info.py"
